on:
  workflow_call:

name: Run npm test and lint

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: '6.2'

    - name: Set up Outfunnel Registry
      run: |
        echo "@outfunnel:registry=https://${{ secrets.OF_REGISTRY_HOST }}/" > .npmrc
        echo "//${{ secrets.OF_REGISTRY_HOST }}/:_authToken=${{ secrets.OF_REGISTRY_TOKEN }}" >> .npmrc

    - name: Read .nvmrc
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      id: nvm

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'

    - run: npm ci
    - run: npm run lint --if-present
    - run: npm run build --if-present
    - run: npm test --if-present
