on:
  workflow_call:
    inputs:
      public_registry:
        description: 'Publish to public registry'
        required: false
        default: false
        type: boolean

name: Publish and tag npm package

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      NODE_ENV: "production"

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Outfunnel Registry
      if: ${{ !inputs.public_registry }}
      run: |
        echo "@outfunnel:registry=https://${{ secrets.OF_REGISTRY_HOST }}/" > .npmrc
        echo "//${{ secrets.OF_REGISTRY_HOST }}/:_authToken=${{ secrets.OF_REGISTRY_TOKEN }}" >> .npmrc

    - name: Set up Public npmjs Registry
      if: ${{ inputs.public_registry }}
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPMJS_REGISTRY_TOKEN }}" > .npmrc

    - name: Read .nvmrc
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      id: nvm

    - name: Read target version
      run: echo ::set-output name=VERSION::$(node -p "require('./package.json').version")
      id: version

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'

    - name: Install dependencies
      run: npm ci || npm install
      env:
        NODE_ENV: development
        
    - run: npm run build --if-present

    - name: Publish the library
      run: npm publish

    - name: Push tag to git
      run: |
        git tag "v${{ steps.version.outputs.VERSION }}"
        git push --tags
