on:
  schedule:
    - cron: "0 8 * * Mon"

name: Weekly Minor Dependency Update

jobs:
  ncu:
    uses: outfunnel/devops-public/.github/workflows/ncu.yml@master
    secrets: inherit
    with:
      target: "minor"
