on:
  schedule:
    - cron: "0 10 1 * *"

name: Monthly Major Dependency Update

jobs:
  ncu:
    uses: outfunnel/devops-public/.github/workflows/ncu.yml@master
    secrets: inherit
    with:
      target: "latest"
